#!/bin/zsh

# Start the session and window 0 in /etc
#   This will also be the default cwd for new windows created
#   via a binding unless overridden with default-path.
tmux new-session -s "$1" -n konsole -d

# Create a bunch of windows in /var/log
windows=('vim' 'workdir' 'ipython' 'sql')
for i in $windows; do
    tmux new-window -d -n "$i"
done

# Select window #1 and attach to the session
tmux select-window -t "$1:0"
tmux -2 attach-session -t "$1"
